name: Scan Daily #VN Stock Bot

on:
  schedule:
    - cron: '30 1 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 420
    defaults:
      run:
        working-directory: vn-stock-bot

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          STOCK_CODES: ${{secrets.STOCK_CODES}}
        run: python main.py
